baseURL = "https://cawnj.github.io"
title = "Hugo ʕ•ᴥ•ʔ Bear Blog"
copyright = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"

enableRobotsTXT = true
disableHugoGeneratorInject = true

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[params]
  description = "Hugo + Bear = :heart:"
  favicon = "images/favicon.png"
  images = ["images/share.webp"]
  dateFormat = "02 Jan, 2006"
  [params.author]
    name = "Conor Joyce"
    email = "conor@cawnj.dev"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
