baseURL: "https://cawnj.github.io"
languageCode: "en-us"
title: "cawnj"
theme: "./.."
relativeURLs: true

googleanalytics: G-H5MK1S5RJT
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: ""

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.jpg"
  name: "Conor Joyce"
  namecolor: ffc107
  profession: "Computer Applications and Software Engineering Student"
  github: "https://github.com/cawnj"
  # gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/conor-joyce-00/"
  # twitter: "https://twitter.com"
  # instagram: "https://instagram.com"
  # facebook: "https://facebook.com"

  # Custom social links
  # customSocialLinks:
  #   # - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #   #   url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "mailto:conor.joyce27@mail.dcu.ie"
  
  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Conor Joyce! I'm a 3rd Year Computer Applications and \
                      Software Engineering student in Dublin City University."
  descripe_l2_person: "I'm a passionate and enthusiastic person and am interested in all things \
                      Programming, DevOps, and Tech."
  skills:
    - name: Python
      percentage: 80
    - name: Go
      percentage: 60
    - name: C
      percentage: 55
    - name: JS
      percentage: 50

  # Experience
  disable_experience: false
  experience:
    - company: "Arista Networks"
      id: "arista"
      role: "Software Engineering Intern"
      startdate: June 2021
      enddate: Sept 2021
      featuredpoints:
        - point: Implementing and deploying a new contract testing framework between microservices.
        - point: Gained experience with Kubernetes, Ansible, Jenkins and Docker.
    - company: "Redbrick (DCU's Networking Society)"
      id: "redbrick"
      role: "Helpdesk"
      startdate: Mar 2021
      enddate: Present
      featuredpoints:
        - point: Technical or services-related help for society members
        - point: Run weekly workshops to teach other society members new and interesting things 
                related to computing or improve their programming skills

  # Education
  disable_education: false
  education:
    - degree: "BSc Honours"
      branch: "Computer Applications (Software Engineering)"
      university: "Dublin City University"
      startedyear: "2019"
      graduation: "2023"
    - degree: "Leaving Cert"
      branch: "477 points"
      university: "Borris Vocational School"
      startedyear: "2013"
      graduation: "2019"
    # - degree: "Degree"
    #   branch: "Branch"
    #   university: "Example university"
    #   startedyear: "year"
    #   graduation: "year"

  # Projects
  disable_projects: true
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "conor.joyce27@mail.dcu.ie"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: true
